### ISSUE TITLE
wsh.go issue on 64Bit systems

### ISSUE THREAD

**Issue by obsti8383** [securitywithoutborders/hardentools#1]
There is an issue with wsh.go on my 64Bit Windows 10 (most probably other 64Bit versions are also affected, see http://windowsir.blogspot.de/2013/03/wow6432node-registry-redirection.html).

Issue is that when creating "Enabled" at
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Script Host\Settings
the real Key is created in 
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows Script Host\Settings

Windows Scripting Host is then not disabled.

The existing code replaced with
    key, _, _ := registry.CreateKey(registry.LOCAL_MACHINE, "SOFTWARE\\Microsoft\\Windows Script Host\\Settings", registry.WRITE **| registry.WOW64_64KEY**)
works. At least when executed with local admin rights.

Without local admin rights this still doesn't work. We have two options:
- write to HKCU only
- verify if HKLM entry create has been successful. If not inform the user that local admin rights are needed (or request local admin rights from windows)

Which way should we go. 

If you give my account access to the repository I can implement that in an experimental branch.

Florian

More Information: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724878.aspx

**Comment by obsti8383** [comment]
Sorry, haven't seen that it is fixed already.

**Comment by obsti8383** [comment]
Just 64Bit issue left.

**Comment by botherder** [comment]
Does this still happen with 64bit? Cause on my Windows 8.1 and Windows 10 64bit the changes seem to work fine.

The other question is if writing to HKCU only is good enough.

**Comment by obsti8383** [comment]
Ah, sorry, indeed it seems to work now. Seems this is different with HKCU.

Regarding "good enough": That depends on what we want to achieve. Of course HKLM would be better, but also needs more involvment from the user and restricts the use for users that have no admin rights. I think an "advanced" module that also hardens HKLM would be an idea for the future.
