### ISSUE TITLE
Query: v2.1

### ISSUE THREAD

**Issue by PeterKW** [securitywithoutborders/hardentools#103]
https://github.com/securitywithoutborders/hardentools/releases/tag/v2.1-rc1

Is there an expected timeline for when version 2.1 moves out of pre-release?

**Comment by Dyras** [comment]
Personally, I would wish to see some kind of timeline for this project. I like HardenTools and all, but it's starting to feel dormant.

**Comment by botherder** [comment]
If there are improvements or features you think are missing, you are more than welcome to submit pull requests. Hardentools is the kind of tool that inevitably hit a slowing stage when the essential functionality is available and working.

**Comment by Dyras** [comment]
Oh I absolutely understand that. I just think there should be more clarity about, that's all :)

A lot of non-nerd people are bound to be discouraged by words like release candidate, for example.

**Comment by botherder** [comment]
I'll let @obsti8383 chime in on that as he's doing most of the developments on this these days, but I imagine the release candidate was to avoid any potential issues deriving from the changes he introduced. I'm sure when a new version will be ready and necessary it will move out of pre-release.

**Comment by Dyras** [comment]
Keep up the good work lads, doing the world a favor!

PS. Consider implementing this https://github.com/securitywithoutborders/hardentools/issues/46 🙂

**Comment by obsti8383** [comment]
@Dyras @PeterKW, @botherder  is absolutely right. We are in quite a slow pace, which in addition to the reason above also lies in my scarce spare time the last months. Did you both test the current pre-release? Asking because I got absolutely no feedback other then #101 (which was negative). If it is working fine from your side I would release it as 2.1.

**Comment by Dyras** [comment]
Works just fine for me!

**Comment by obsti8383** [comment]
Released v2.1.
