### ISSUE TITLE
pdf and video streaming not working

### ISSUE THREAD

**Issue by bilsby** [securitywithoutborders/hardentools#112]
For some reason video streaming and pdf in browser is not working
it gives an audio render error that is not corrected by reinstalling the drivers
Anyway to reverse hardentool changes
Also firefox works fine just brave, chrome and edge browser malfunctioning

**Comment by obsti8383** [comment]
Hi @bilsby, 

none of the modules of hardentools should affect browsers, especially video rendering or pdf in browser.

You can revert the effect or hardentools by starting it again an select "Restore", see README.md.

Have you used any other harden scripts?

Is the effect reverted after restoring with hardentools and rebooting the system?

**Comment by bilsby** [comment]
Hello

Thank you. I will try to reverse it and see and let you know.

Thank you
