### ISSUE TITLE
Stretching the window = broken window

### ISSUE THREAD

**Issue by 77ZaRR77** [securitywithoutborders/hardentools#113]
Stretched the window and it broken, completely gray coloured.
I don't think posting screenshot will make any sense.
Log says a lot of times: 
`Error 502 in GL Renderer
At: /home/travis/gopath/pkg/mod/fyne.io/fyne@v1.3.0/internal/painter/gl/gl_core.go:92`

If not stretching it, works good!

**Comment by obsti8383** [comment]
Hi @77ZaRR77, thanks for your report. What version of hardentools are you using? 

If it is older than v2.1, could you please try with this release or one of the newer beta releases?

Thanks,
obsti8383

**Comment by obsti8383** [comment]
Note to myself: Could be related to https://github.com/fyne-io/fyne/issues/1461

**Comment by obsti8383** [comment]
Hi @77ZaRR77, do you still experience this issue, also with hardentools >= 2.1?
