### ISSUE TITLE
Windows security protection history

### ISSUE THREAD

**Issue by Aman1337g** [securitywithoutborders/hardentools#115]
Whenever I harden my sytem and restart windows there is this log generated in windows security protection history
![Screenshot (51)](https://user-images.githubusercontent.com/97891757/180037017-e5247aa8-b945-4154-9810-c4cffa3a3426.png)
.

**Comment by obsti8383** [comment]
HI @Aman1337g,

i have no real experience with Windows 11 yet, but I'm also getting some of these notifications on my test system (e.g. from WmiPrvSE.exe, msiexec.exe, MicrosoftEdgeUpdate.exe).

Microsofts comment in general is:

> I recently enabled the ASR rule, 'Block credential stealing from the Windows local security authority subsystem (lsass.exe)', and 
> I am getting a large number of notifications. What is going on?
> 
> A notification generated by this rule does not necessarily indicate malicious activity; however, this rule is still useful for blocking malicious activity, since malware often targets lsass.exe to gain illicit access to accounts. The lsass.exe process stores user credentials in memory after a user has logged in. Windows uses these credentials to validate users and apply local security policies.
> 
> Because many legitimate processes throughout a typical day will be calling on lsass.exe for credentials, this rule can be especially noisy. If a known legitimate application causes this rule to generate an excessive number of notifications, you can add it to the exclusion list. Most other ASR rules will generate a relatively smaller number of notifications, in comparison to this one, since calling on lsass.exe is typical of many applications' normal functioning.

Source: <https://docs.microsoft.com/de-de/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq?view=o365-worldwide>

So this seems to be quite normal, e.g. from applications like TaskManager that enumerate all proccesses. But what I don't understand yet is, why these notifications only pop up on my Windows 11 installation, not in Windows 10.

So hopefully everything is fine in your case. If someone knows more about this issue please comment.

Florian
