### ISSUE TITLE
Enabling Harden Tools increases ping in some online games.

### ISSUE THREAD

**Issue by johnnymatthews** [securitywithoutborders/hardentools#118]
This may be anecdotal, so I'm interested to see if other folks are experiencing the same thing. When Harden Tool are enabled (just the standard set, I haven't ventured into the Advanced options just yet), my ping in online games goes from ~20 to ~250 -- making things unplayable.

An obvious work around is to disable Harden Tools when I wanna play, and re-enable them once I'm done. But I'd prefer not to have to do that. If there's a single Harden Tool rule to disable that'll leave my ping alone, that'd be ideal.

So, anyone else experienced this ping issue? Anyone know which settings I can disable to help?

**Comment by obsti8383** [comment]
@johnnymatthews i can hardly guest what could cause this since none of the changes should affect the network stack. Can you see this effect with standard "ping" command line tool in Windows? Or how could we try to reproduce this?

**Comment by johnnymatthews** [comment]
So now I've no idea what's going on. I just tried playing a few games with Harden Tools enabled and my ping was normal. Clearly Harden Tools isn't the problem. Sorry for the time waste! Closing.
