### ISSUE TITLE
Granular hardening

### ISSUE THREAD

**Issue by mmiszczyk** [securitywithoutborders/hardentools#17]
I think hardentools would be more useful if there were some settings there (might be hidden behind a 'settings' button or something like that if you want to preserve its easy to use nature) to allow e.g. disabling VBscript but not cmd/powershell. I get that power users and sysadmins are not the primary target of this because they generally know how to modify the registry but this could be a good way to automate it.

**Comment by obsti8383** [comment]
I agree, Nex and I also have discussed that already.

**Comment by massar** [comment]
I suggest the following things:

 - add a init() function to each module that calls a register function, that registers the trigger_xxx function. The register_trigger() then maintains a list, the UI would allow 'advanced' users to select/deselect items. The trigger_all() function just loops over that list, as it knows how many are enabled it can even have a semi-reasonable progress bar as it knows at which module it is.

- move windows dependencies from main to main_windows.go for instance.

 - add a _windows postfix to most module files (eg ```explorer_windows.go```), that is the ones that are windows specific (thus allowing us next to make a _osx module and voila, the windows edition gets only windows-specific stuff and the osx edition only osx specific stuff and a linux... ;) )


If wanted, I can prep a MR for this so one can see how it looks like ;)

**Comment by braian87b** [comment]
It will be great to generate a ini file with all features with like 'disable_wsh=1', then we could edit that file and disable the things that we don't want to modify, in that way there is no need to make an undo function neither.

**Comment by obsti8383** [comment]
I would suggest that we also add a function to get the current status (hardened true/false) to be able to show that in the GUI)

**Comment by Velocet** [comment]
You might consider that this tool maybe should get a rewrite in PoSh or as a C# (WPF) application (like mentioned [here](https://github.com/securitywithoutborders/hardentools/issues/31#issuecomment-323833913)).

**Pros:**

- Visual Studio Community/VScode/PoSh ISE makes development easier when handling a GUI
- More powerful
- Two choices for distribution: PoSh script or executable (would be better for sys admins?)

**Cons:**

- Rewrite :(

**Comment by ccoenen** [comment]
Please don't hijack issues. A rewrite in a different language can be discussed in its own issue.

**Comment by botherder** [comment]
@massar I like the changes you suggest, and I'd be happy to see a PR with these changes.
