### ISSUE TITLE
Command-line terminal disabled altogether?

### ISSUE THREAD

**Issue by ubestemt** [securitywithoutborders/hardentools#19]
The README says that "after running Hardentools you won't be able, for example, to [...] use the Command-line terminal". But it also states that hardentools "[d]isables powershell.exe, powershell_ise.exe and cmd.exe execution via Windows Explorer." So is the Command-line terminal disabled altogether or only when launched by Windows Explorer?

**Comment by IMNAE** [comment]
Both are disabled as you can start powershell using cmd.exe /c powershell.exe
There is talk about letting users have more granularity with what options they disable, this would allow power users to still have cmd.exe. That would be for future versions though.

**Comment by obsti8383** [comment]
cmd.exe (and powershell.exe) is only disabled when started via explorer. If you use another tool to start cmd.exe that usually works (for instance with FreeCommander)

**Comment by Kwpolska** [comment]
That’s so dumb. Malware can just use a small .exe that runs PowerShell/cmd and work around this “mitigation” — and that will be more believable than having people run `.bat` or `.ps1` files. On the other hand, I’ve been asked by tech support to open `cmd.exe`, so not only power users need it.

**Comment by xorred** [comment]
I see this as a problem as well, but one can run cmd and powershell from process explorer or process hacker - so IT admins will still be unaffected.

**Comment by botherder** [comment]
I am also dubious about this, generally, but given that it is configurable I don't think it's too problematic. Perhaps it should be disabled by default? @obsti8383?

**Comment by obsti8383** [comment]
Hi @botherder Disallowing the start of cmd.exe via Explorer is currently in one module together with disabling powershell.exe and powershell_ide.exe. This is because we use the same registry key. If we only want to exclude cmd.exe we have to move this to a separate module and add some logic. Or we disable the whole module?

**Comment by botherder** [comment]
If we were to disable the cmd.exe change, I would separate it from the PowerShell module and keep PowerShell as is.
