### ISSUE TITLE
harden/restore instead of enable/disable?

### ISSUE THREAD

**Issue by ccoenen** [securitywithoutborders/hardentools#20]
I have some of the settings applied manually already. If I were to try out the program and (for whatever reason) didn't like what I just did, and disabled the changes, I would fall back to a worse state than I started. Mainly because most settings are reset to (I guess?) factory defaults.

I'd like to propose a long-term change where the program keeps track of the previous state when overwriting it. So that I can roll back to _that_ instead of completely disabling to factory default.

This would also make tinkering with it easier once https://github.com/securitywithoutborders/hardentools/issues/17 is a thing.

**Comment by obsti8383** [comment]
Had the same thought already. I'm doing some thing like this in https://github.com/obsti8383/hardentools/blob/fixpowershell/powershell.go already (no pull request yet for that - waiting for UAC pull).
My idea was to use registry to remember the old settings.

**Comment by botherder** [comment]
I agree to these points. The blocking factor for me is the GUI really.

**Comment by obsti8383** [comment]
@botherder I would propose just like ccoenen recommended above to use the wording "harden" and "restore" in the code and make clear in the output and comments if it is really a "restore" or a "reset to defaults". And to remedy misunderstandings I would change the bool meaning in the trigger functions to do hardening if value is "true" and revert if it is "false". OK with you? (Then we can gradually move from reverting to defaults to reverting to the former state.)

**Comment by botherder** [comment]
That's fine for me, yes.

**Comment by obsti8383** [comment]
@ccoenen @botherder Please review pull request #22

**Comment by botherder** [comment]
I guess this is safe to close.

**Comment by ccoenen** [comment]
Actually, this is not completely done in #22, see [this comment](https://github.com/securitywithoutborders/hardentools/pull/22#issuecomment-294483772). The main point of this issue was not addressed in that pull request.

**Comment by botherder** [comment]
Any thoughts on how to bring it forward? Would be good to have a new release done soon.

**Comment by obsti8383** [comment]
working on it, see:
- seems to work fine: https://github.com/obsti8383/hardentools/blob/master/autorun.go
- not tested yet: https://github.com/obsti8383/hardentools/blob/master/office.go

**Comment by obsti8383** [comment]
short update: office.go (in my repo, see above) had some issues that are fixed now. Please feel free to test.

I'll try to rewrite the other modules within the next days and then create a pull request.

**Comment by obsti8383** [comment]
Please test now using https://github.com/obsti8383/hardentools 
I've also created a pull request (#26)

**Comment by obsti8383** [comment]
Anybody had the chance to do some testing yet?
