### ISSUE TITLE
Usability review of Hardentools

### ISSUE THREAD

**Issue by ei8fdb** [securitywithoutborders/hardentools#28]
After a Twitter request for usability input into Hardentools, I've been speaking with @botherder on Mattermost.

From our discussion he's concerned with:

1. the GUI "being ugly"
2. the progress bar is pretty much fake. Th progress is too quick - you click on the button (which is awkwardly large and thin) and boom, it's done
3. the need for GUI to allow to enable/disable single features

As a beginning, I suggested the best thing would be for me to run it and do what's called an usability (expert) review - where the reviewer "pretends" to be a user, try to think how they think, do what they do. 

When doing a usability review we use well established [usability heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/) to keep focused on what he user would do. 

These include important heuristics like: visibility of what the system is doing, preventing the user from making mistakes, helping the user to recover from errors - system or user, consistency. 

This would deal with 1 and 2 above. 

Once this is done, I'd post the results here and we can discuss how to deal with them. 

What do you think about that?

**Comment by botherder** [comment]
:+1:

**Comment by Velocet** [comment]
I am not that much into Go but i think this could be better/easier achieved through UWP/WPF. Development in [Visual Studio Community](https://www.visualstudio.com/vs/community) would also be free.

UX/UI: Maybe a look at some other privacy tools is advised:
[Privacy Repairer](https://www.securilla.com/privacy-repairer)
[WPD](https://getwpd.com/)
[O&O ShutUp10](https://www.oo-software.com/de/shutup10)
[DoNotSpy10](http://pxc-coding.com/de/portfolio/donotspy10/) (i like the explanations on the right)

I would also suggest two settings:
- Normal UI which is just plain simple (KISS) like it is now
- "Expert UI" which expandes some kind of terminal window at the bottom where one could see the progress and what the app is doing

A "Do All" button would also be nice for people that are not that much into PCs and just wanna harden the system with a one-click-solution.

**Comment by obsti8383** [comment]
What do you think?




![hardentools_gui](https://user-images.githubusercontent.com/16605975/32702472-0b0adf4e-c7e8-11e7-9d49-a9fa8fa43c52.jpg)

**Comment by botherder** [comment]
That definitely looks a lot better!
Would be great if the expert settings could be expanded.

**Comment by obsti8383** [comment]
@nex: What do you mean by expanded?

**Comment by botherder** [comment]
I mean like, hidden then expanded through a button. But it is not really necessary.

**Comment by botherder** [comment]
@obsti8383 I noticed that when you uncheck one option, run Harden, and then run Restore afterwards, all checkboxes are still checked (not showing which have been left untouched and therefore need no restoring). Do you think it's possible to fix that?

**Comment by obsti8383** [comment]
@botherder : That thing in your last comment should be fixed with #42. Only issue here is, that if hardening has only be partially successful or the user has changed a setting in the meantime, the other settings won't be restored right now (see also "improvement" in comment in #42).
