### ISSUE TITLE
Request for user related "design" label to be added to issue tracker

### ISSUE THREAD

**Issue by ei8fdb** [securitywithoutborders/hardentools#29]
As a follow-up to issue #28, I'd like to request a user related label to be added. I don't think I can add it.

This helps UX people identify user related requests to start working on.

If there's lots, we can add others, but as a beginning the label "design" would be a good start.

What do you think?

**Comment by obsti8383** [comment]
@botherder Does make sense I think. Could you add that in github?

**Comment by botherder** [comment]
Done.
