### ISSUE TITLE
Adobe Reader Enhancements

### ISSUE THREAD

**Issue by obsti8383** [securitywithoutborders/hardentools#32]
Adobe PDF module could need some enhancements to cover all the most important security settings:
- Switch on the Protected Mode setting under "Security (Enhanced)" (enabled by default in current versions) (HKEY_LOCAL_USER\Software\Adobe\Acrobat Reader\<version>\Privileged -> DWORD „bProtectedMode“ = 1)
- Switch on Protected View for all files from untrusted sources (HKEY_CURRENT_USER\SOFTWARE\Adobe\Acrobat Reader\DC\TrustManager -> iProtectedView = 1)
- Switch on Enhanced Security setting under "Security (Enhanced)" (enabled by default in current versions) (HKEY_CURRENT_USER\SOFTWARE\Adobe\Acrobat Reader\DC\TrustManager -> bEnhancedSecurityInBrowser = 1 & bEnhancedSecurityStandalone = 1)

**Comment by Velocet** [comment]
I would suggest to check/set/reset all options that are security related, like:
- Check/Enable automatic installation of updates
