### ISSUE TITLE
Optional ON-OFF

### ISSUE THREAD

**Issue by bobybobybob** [securitywithoutborders/hardentools#36]
Disables powershell.exe, powershell_ise.exe and cmd.exe execution via Windows Explorer. You will not be able to use the terminal and it should prevent the use of PowerShell by malicious code trying to infect the system.

---------------
I need CMD, how turn it on?   Would better that user can chose what is on and off.

**Comment by obsti8383** [comment]
Hi, you can just remove the relevant key using regedit.exe in your users profile under Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\DisallowRun and reboot to reactivate cmd.exe (Please be careful when using regedit.exe.
We are working on the user chosing / GUI.

**Comment by botherder** [comment]
This is basically relevant to #17. I'll close this ticket.
