### ISSUE TITLE
Show file extensions

### ISSUE THREAD

**Issue by Dyras** [securitywithoutborders/hardentools#47]
Greetings! I think Hardentools should make Windows show file extensions for all files. Can be done easily with regedit:
http://www.itprotoday.com/management-mobility/how-can-i-modify-registry-enable-option-show-file-extensions-windows-explorer
https://www.youtube.com/watch?v=M2LXhroaDEo

Would really help people differentiate between cat.jpg and cat.jpg.exe

**Comment by obsti8383** [comment]
fixed in #49
