### ISSUE TITLE
Disable WPAD

### ISSUE THREAD

**Issue by mschilt** [securitywithoutborders/hardentools#56]
WPAD is totally useless and exposes your client to unnecessary MITM situations and potatos stealing your hashes. 

Suggested steps:
1. Disable the service “WinHTTP Web Proxy Auto-Discovery Service”
(HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\WinHttpAutoProxySvc\Start -> 4)
1. echo "255.255.255.255 wpad." >> c:\windows\system32\drivers\etc\hosts
1. "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Wpad\WpadOverride"  -> 0

**Comment by Velocet** [comment]
Good point but i wouldn't alter the hosts file since you don't have to do this after the service is disabled.

**Comment by mschilt** [comment]
Looks like MS just put the javascript interpreter they used in WPAD into their JS sandbox (.. .pac files are JS).  This should reduce the attack surface a lot. However not everyone runs the latest version.

See https://twitter.com/epakskape/status/1007316208087994368

**Comment by pich4ya** [comment]
Disable LLMNR / Netbios-NS.

**Comment by m3ch-mania** [comment]
I recommend against disabling the WinHTTP WPAD service. Though not properly documented on Microsoft's website, disabling this service in newer versions of Windows will lead to eventual resource exhaustion issues.

**Comment by infosecmatt** [comment]
@m3ch-mania could you clarify how it would cause resource exhaustion issues?

**Comment by m3ch-mania** [comment]
We opened up a case with MSFT after some of our Hyper-V cluster hosts kept hanging up and forcefully restarting. Their RCA determined that having the WinHTTP WPAD service disabled was the cause. You can see on [this ServerFault question](https://serverfault.com/a/762987) that this is somewhat of a known-issue.

In short, the WinHTTP stack expects that the `WinHttpAutoProxySvc` service can be started and stopped as needed. If the service is disabled, the system will start to accumulate stuck threads (all pending an API response) until resource exhaustion eventually renders the system unresponsive.

**Comment by m3ch-mania** [comment]
See also: [MSKB Archive #2870551](https://mskb.pkisolutions.com/kb/2870551)

**Comment by infosecmatt** [comment]
@m3ch-mania Thanks, appreciate the thorough response.

**Comment by obsti8383** [comment]
Close due to risk / gain ratio doesn't look favorably according to the last comments.
