### ISSUE TITLE
Small Word DDE Hardening improvement

### ISSUE THREAD

**Issue by obsti8383** [securitywithoutborders/hardentools#63]
Microsoft disabled DDE in Word with Office Update ADV170021 update. We should make sure that it is in default (disabled) state:

This update adds a new Windows registry key that controls the DDE feature's status for the Word app. The default value disables DDE. Here are registry key's values:

1. In the Registry Editor navigate to \HKEY_CURRENT_USER\Software\Microsoft\Office\version\Word\Security AllowDDE(DWORD)
2. Set the DWORD value based on your requirements as follows:

AllowDDE(DWORD) = 0: To disable DDE. This is the default setting after you install the update.
AllowDDE(DWORD) = 1: To allow DDE requests to an already running program, but prevent DDE requests that require another executable program to be launched.
AllowDDE(DWORD) = 2: To fully allow DDE requests.

**Comment by botherder** [comment]
:+1:
