### ISSUE TITLE
Disable MHT

### ISSUE THREAD

**Issue by Monter** [securitywithoutborders/hardentools#73]
See https://betanews.com/2019/04/15/internet-explorer-mht-vulnerability/

**Comment by obsti8383** [comment]
Could disabling MHT have an impact on end users? Does anyone really use MHT these days?

**Comment by beerisgood** [comment]
@obsti8383 i can only speak for me, but as IT "pro user" i never use any MHT files
And the security impact here is higher then the few people which realy use that files nowadays

**Comment by Monter** [comment]
Most users, however, are not PRO users.
Browsers (including chrome) still allow opening and writing to MHT format.

**Comment by beerisgood** [comment]
In your opinion no security settings would exist.

Also this is about System, not Browser

**Comment by Monter** [comment]
I do not know what you mean,
I just think that if this type of file is a threat and is still supported by the system, the curing tool should have the option of blocking this type of files in the same way as disabling the script host prevents the execution of JS files. That's all.

**Comment by beerisgood** [comment]
I don't get what you want here.
First you suggest disable .mht files but then you disagree.

Your example with script host is invalid. That's not possible with all files but doesn't matter cause the result is the same.

Last but not least we should increase the security at all with this project here.
And if users really need some stuff, they can re-enable it

**Comment by Monter** [comment]
I suggested adding the option to disable MHT files as a program option and I still suggest it. I did not cancel anything, maybe we did not understand each other.
No matter, you will do as you like.

**Comment by beerisgood** [comment]
@botherder 
@eschaefer

I vote for reopen this issue and include blocking .MHT

**Comment by botherder** [comment]
Merged. Thanks all for the help on this.
