### ISSUE TITLE
Additional LSA protection

### ISSUE THREAD

**Issue by emdel** [securitywithoutborders/hardentools#77]
This can be a nice feature: 
https://twitter.com/oddvarmoe/status/1196330474970501120?s=21

We should test it and understand when is effective.

**Comment by obsti8383** [comment]
Yes, sounds interesting. Would be interesting if this really helps for non-domain joined devices (or if it is then easier to steal credentials e.g. using a keylogger). Anyhow this is quite easy to implement, but we need to know and document what is the impact (e.g. in Enterprise environments it could have some impact according to Microsoft on LSA plugins and drivers -> https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection). 
Somebody has some time to fire up his Mimikatz?

**Comment by obsti8383** [comment]
@emdel If you would like to test, heres a binary: [https://github.com/obsti8383/hardentools/releases/tag/fp0.5.1](https://github.com/obsti8383/hardentools/releases/tag/fp0.5.1)
and heres the source: [https://github.com/obsti8383/hardentools](https://github.com/obsti8383/hardentools)
