### ISSUE TITLE
command line options?

### ISSUE THREAD

**Issue by sokatra** [securitywithoutborders/hardentools#79]
hy, good project, but i can't find commandline options?

For me it is essential that i can deploy this package as a script.
i this isn't possible it was a major disadvantage. i recommend to leave normal cmd as eecutable and just deny powershell and all the other settings.

**Comment by botherder** [comment]
It is not a command-line tool, nor a script. It is not meant for automated/enterprise use.

**Comment by RTechSn** [comment]
Not having command line options defeats the purpose of having cli version of the program.
Seems like such a trivial thing to implement.

**Comment by obsti8383** [comment]
@RTechSn There are two command line options, -harden and -restore. Still additional options on what should be hardened would be nice. PRs always very welcome.
