### ISSUE TITLE
Windows 10 Home and disable CMD

### ISSUE THREAD

**Issue by MichalGizaSrv** [securitywithoutborders/hardentools#84]
Hi! I disabled CMD in Hardentools. Now, I can't enable it. I try use your tool and registry (https://www.maketecheasier.com/disable-command-prompt-windows/) because gpedit isn't installed on Home version of Windows.

How do you disable CMD in Hardentools on Windows 10 Home?

**Comment by obsti8383** [comment]
Hi, is there an error message in hardentools when you are restoring? 
Hardentools should also generate a hardentools.log file. Could you please check this for errors when restoring?
Also have you rebooted your Windows?

**Comment by MichalGizaSrv** [comment]
> Hi, is there an error message in hardentools when you are restoring?
> Hardentools should also generate a hardentools.log file. Could you please check this for errors when restoring?
> Also have you rebooted your Windows?

I don't see any errors and haven't *.log file. Yes, I rebooted system

**Comment by obsti8383** [comment]
Ah, that is strange. It should normally be in the folder where you started hardentools from. Anyhow, could you please hit Win+R and enter regedit.exe and tell me if there is one of the following entries, and if yes, with which content?

Entries below Key / Folder (see example screenshot): _HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\DisallowRun_

![disallowrun](https://user-images.githubusercontent.com/16605975/84109845-e6bdd800-aa23-11ea-83bd-2057ed808023.jpg)


Entries below Key / Folder : _HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer_

The above keys are used by Hardentools to disable cmd.exe

Entries below Key / Folder: _HKEY_CURRENT_USER\Software\Security Without Borders_

These are entries from hardentools to save the existing configuration before hardening.

Thx.

**Comment by MichalGizaSrv** [comment]
Sorry for late.

(https://user-images.githubusercontent.com/58888243/84669055-b0e98980-af24-11ea-8f9c-882eb731bb4b.png)

(https://user-images.githubusercontent.com/58888243/84669093-bf37a580-af24-11ea-8ec9-92f8d4de7996.png)

**Comment by obsti8383** [comment]
@MichalGizaSrv OK, obviously restoring the settings with hardentools didn't go through since the key "Harden" is set to "1". But that was clear anyhow. 
First proposal: Could you try again to start hardentools and hit the restore Button and check if there are any messages in the log output?
Alternate proposal: You could just set the "DisallowRun" key below Policies/Explore to "0". That should at least fix your cmd.exe problem. But other settings will still be hardened. You can find all the settings that have been changed using the SavedState_* keys, but you have to know what your are doing if you want to manually revert.

**Comment by MichalGizaSrv** [comment]
> @MichalGizaSrv OK, obviously restoring the settings with hardentools didn't go through since the key "Harden" is set to "1". But that was clear anyhow.
> First proposal: Could you try again to start hardentools and hit the restore Button and check if there are any messages in the log output?
> Alternate proposal: You could just set the "DisallowRun" key below Policies/Explore to "0". That should at least fix your cmd.exe problem. But other settings will still be hardened. You can find all the settings that have been changed using the SavedState_* keys, but you have to know what your are doing if you want to manually revert.

I want unlock only CMD so I will use registry. Thank you for your help :)
