### ISSUE TITLE
Unable to create window

### ISSUE THREAD

**Issue by brucbr** [securitywithoutborders/hardentools#91]
```
2020/09/06 02:24:47 Fyne error:  window creation error
2020/09/06 02:24:47   Cause: APIUnavailable: WGL: The driver does not appear to support OpenGL
2020/09/06 02:24:47   At: /home/travis/gopath/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/window.go:1133
```

**Comment by obsti8383** [comment]
@brucbr Does this occur in a Virtual Machine or when using RDP to access the machine?

If yes this is a known issue (sorry, not documented yet) with the fyne.io UI framework ([https://github.com/fyne-io/fyne/issues/410](https://github.com/fyne-io/fyne/issues/410)). We are working on a command line interface to remediate that at least a bit (see #90)

**Comment by obsti8383** [comment]
Added known issues to README.md: https://github.com/securitywithoutborders/hardentools/blob/master/README.md#known-issues

**Comment by brucbr** [comment]
It's just on my laptop. No virtual machine or Remote Desktop is being used. It's a fresh windows install just after all drivers from Dell installed.

**Comment by brucbr** [comment]
@obsti8383 Reinstalled windows and drivers again....

Working now. I don't know what caused the issue.
