### ISSUE TITLE
OpenGL missing? Why do you even need it to run this tool?

### ISSUE THREAD

**Issue by atlantsecurity** [securitywithoutborders/hardentools#97]
2021/03/10 23:55:19 Fyne error:  window creation error
2021/03/10 23:55:19   Cause: APIUnavailable: WGL: The driver does not appear to support OpenGL
2021/03/10 23:55:19   At: /home/travis/gopath/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/window.go:1133

what is the logic to require openGL for this app which just shows text-based interface?

**Comment by obsti8383** [comment]
Hi @atlantsecurity, actually hardentools is a UI tool, please take a look at the readme.md. If you want you can already take a peak at a beta version for a simple cli usage -> https://github.com/obsti8383/hardentools/releases/tag/2.1beta2 (use the "hardentools-cli.exe" with "-harden" for hardening all default settings (or "-restore" for reverting).
Please be aware that this tool is only made for unmanaged (non-domain joined) Windows 10 clients, not servers.

**Comment by atlantsecurity** [comment]
I know all that. But Amazon Workspaces hardening, which they advertise as W10, disagrees. Turns out Workspaces is actually server 2016. The UI libraries you use are not portable enough to work on limited W10 or Amazon's flavor of Windows 10.

**Comment by obsti8383** [comment]
As said: If you want you can already take a peak at the command line beta version for a simple cli usage -> https://github.com/obsti8383/hardentools/releases/tag/2.1beta2 (use the "hardentools-cli.exe" with "-harden" for hardening all default settings (or "-restore" for reverting).
