### ISSUE TITLE
CLI calls GUI for info/error boxes, fails.

### ISSUE THREAD

**Issue by x-t** [securitywithoutborders/hardentools#99]
On an [AME install](https://ameliorated.info), Windows Defender is disabled by default. This will make `hardentools-cli.exe` attempt to throw an info box, it calls [gui.go#L251](https://github.com/securitywithoutborders/hardentools/blob/master/gui.go#L251) from `windows_asr.go` [#L293](https://github.com/securitywithoutborders/hardentools/blob/d7a18eacdd5975e18ea3d452accc7fecdeea773f/windows_asr.go#L293), [#L276](https://github.com/securitywithoutborders/hardentools/blob/d7a18eacdd5975e18ea3d452accc7fecdeea773f/windows_asr.go#L276), and then panics. Same behavior is when an error is thrown from elsewhere, as it calls [gui.go#L239](https://github.com/securitywithoutborders/hardentools/blob/master/gui.go#L239).

**Comment by obsti8383** [comment]
Hi @x-t, thanks for the report. Should be fixed now on this release here: https://github.com/obsti8383/hardentools/releases/tag/2.1beta3
